# incomplete. Never executed.

# pip install conan
FROM python:3.6-alpine
RUN apk add g++
RUN pip install numpy
# more in https://stackoverflow.com/questions/33421965/installing-numpy-on-docker-alpine
